Refresh the autogenerated code for the signer
This latest googleapi was causing the old code to fail with the following
error:

	go/src/v.io/x/ref/services/internal/restsigner/v1/signer-gen.go:106: undefined: googleapi.SetOpaque